# Generated by Django 5.0.7 on 2024-08-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_author_age_alter_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='age',
            new_name='ISBN',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.author'),
        ),
    ]
