# Generated by Django 5.0.7 on 2024-08-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_age_author_isbn_remove_author_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ISBN',
            new_name='published_year',
        ),
    ]
